ft_right_foot_air:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
ft_right_foot_gnd:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
ft_left_foot_air:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
ft_left_foot_gnd:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
