# defines joints to be controlled by l3 module
joints:
  ["l_leg_hip_y",
   "l_leg_hip_r",
   "l_leg_hip_p",
   "l_leg_kn_p",
   "l_leg_an_p",
   "l_leg_an_r",
   "r_leg_hip_y",
   "r_leg_hip_r",
   "r_leg_hip_p",
   "r_leg_kn_p",
   "r_leg_an_p",
   "r_leg_an_r"]
