plugin_sets:
  robotis_walk:
    # Walk controller using l3_step_control
    l3_step_walk_controller: none

    # LIPMBalanceControllerPlugin
    robotis_lipm_balance_controller:
      params:
        preview_time: 1.6
        time_unit: 0.008
        gravity: 9.81

    # JointBalanceControllerPlugin
    robotis_joint_balance_controller: 
      params:
        gravity: 9.81
        fsp_ratio: 0.2
        start_step_duration: 3.2
        end_step_duration: 1.6
        param_update_duration: 2.0
        time_unit: 0.008 

        ft_weights: [0.001, 0.001, 0.001, 1.0, 1.0, 0.0]
        ft_p_gains: [0.05, 0.05, 0.02, 0.0015, 0.0015, 0.0]
        ft_d_gains: [0.001, 0.001, 0.001, 0.0002, 0.0002, 0.0]

        imu_weights: [1, 0.1, 1, 0.1]
        imu_p_gains: [1.0, 0.3, 1.0, 0.3]
        imu_d_gains: [0.0, 0.0, 0.0, 0.0]

        leg_controller_names: ["x_force_controller", "y_force_controller", "z_force_controller", "pitch_torque_controller", "roll_torque_controller", "yaw_torque_controller"]
        imu_controller_names: ["roll_orientation_controller", "roll_gyro_controller", "pitch_orientation_controller", "pitch_gyro_controller"]

        imu_cut_off_freq: 12.0
        ft_cut_off_freq: 10.0
        x_offset_cob: -0.015
        y_offset_cob: 0.0

    # ZMPGaitGeneratorPlugin
    robotis_zmp_schedule_planner: 
      params:
        time_unit: 0.008
        preview_time: 1.6
        min_reserved_steps: 2
        start_step_duration: 3.2
        fsp_ratio: 0.2

    # ZMPReferenceGeneratorPlugin
    robotis_zmp_reference_generator: 
       params:
        time_unit: 0.008
        preview_time: 1.6

    # FootTrajectoryGeneratorPlugin
    foot_trajectory_generator: 
      params:
       z_swap_value: 0.1 

    # BodyTrajectoryGeneratorPlugin
    body_trajectory_generator:
      params:
       z_swap_value: 0.01

    # Interface Plugins
    imu_sensor_topic:
      params:
        topic: "/johnny5/sensor/imu/raw"

    joint_states: thor_mang_joint_states

    left_foot_ft:
      import: thor_mang_ft_sensor
      params:
        leg_index: 0
        sensor_name: "l_foot"
        frame_id: "l_foot_ft_link"
        use_scaled: True

    right_foot_ft:
      import: thor_mang_ft_sensor
      params:
        leg_index: 1
        sensor_name: "r_foot"
        frame_id: "r_foot_ft_link"
        use_scaled: True

    leg_joint_cmd: thor_mang_joint_cmd_interface

    leg_joint_cmd_topic:
      import: joint_cmd_interface_topic
      params:
        ns: "/johnny5/joints/"
        joints:
          ["l_leg_hip_y", "l_leg_hip_r", "l_leg_hip_p", "l_leg_kn_p", "l_leg_an_p", "l_leg_an_r",
           "r_leg_hip_y", "r_leg_hip_r", "r_leg_hip_p", "r_leg_kn_p", "r_leg_an_p", "r_leg_an_r"]
