plugin_sets:
  robotis_walk:
    # Walk controller using l3_step_control
    l3_step_walk_controller: none

    # LIPMBalanceControllerPlugin
    robotis_lipm_balance_controller: none

    # JointBalanceControllerPlugin
    robotis_joint_balance_controller: none

    # ZMPGaitGeneratorPlugin
    robotis_zmp_schedule_planner: 
      params:
        time_unit: 0.008
        preview_time: 1.6

    # ZMPReferenceGeneratorPlugin
    robotis_zmp_reference_generator: 
       params:
        time_unit: 0.008
        preview_time: 1.6

    # FootTrajectoryGeneratorPlugin
    foot_trajectory_generator: 
      params:
       z_swap_value: 0.01 

    # BodyTrajectoryGeneratorPlugin
    body_trajectory_generator:
      params:
       z_swap_value: 0.01       

    # KinematicsPlugin
    kdl_kinematics:
      params:
        robot_description: "/johnny5/robot_description"

    # GaitGeneratorPlugin
    bipedal_gait_generator: none

    # Interface Plugins
    imu_sensor_topic:
      params:
        topic: "/johnny5/sensor/imu/raw"

    joint_states: thor_mang_joint_states

    left_foot_ft:
      import: thor_mang_ft_sensor
      params:
        sensor_name: "l_foot"
        frame_id: "l_foot_ft_link"
        use_scaled: True

    right_foot_ft:
      import: thor_mang_ft_sensor
      params:
        sensor_name: "r_foot"
        frame_id: "r_foot_ft_link"
        use_scaled: True

    leg_joint_cmd: thor_mang_joint_cmd_interface

    leg_joint_cmd_topic:
      import: joint_cmd_interface_topic
      params:
        ns: "/johnny5/joints/"
        joints:
          ["l_leg_hip_y", "l_leg_hip_r", "l_leg_hip_p", "l_leg_kn_p", "l_leg_an_p", "l_leg_an_r",
           "r_leg_hip_y", "r_leg_hip_r", "r_leg_hip_p", "r_leg_kn_p", "r_leg_an_p", "r_leg_an_r"]
