plugin_sets:
  robotis_walk:
    # GaitPatternGeneratorPlugin
    robotis_gait_pattern_generator: none

    # LIPMBalanceControllerPlugin
    robotis_feet_balance_controller: none

    # JointBalanceControllerPlugin
    robotis_joint_balance_controller: none

    # KinematicsPlugin
    kdl_kinematics: none

    # Interface Plugins
    imu_sensor_topic:
      params:
        topic: "/johnny5/sensor/imu/raw"

    joint_states: thor_mang_joint_states

    left_foot_ft:
      import: thor_mang_ft_sensor
      params:
        sensor_name: "l_foot"
        frame_id: "l_foot_ft_link"
        use_scaled: True

    right_foot_ft:
      import: thor_mang_ft_sensor
      params:
        sensor_name: "r_foot"
        frame_id: "r_foot_ft_link"
        use_scaled: True

    leg_joint_cmd: thor_mang_joint_cmd_interface

    leg_joint_cmd_topic:
      import: joint_cmd_interface_topic
      params:
        ns: "/johnny5/joints/"
        joints:
          ["l_leg_hip_y", "l_leg_hip_r", "l_leg_hip_p", "l_leg_kn_p", "l_leg_an_r", "l_leg_an_p",
           "r_leg_hip_y", "r_leg_hip_r", "r_leg_hip_p", "r_leg_kn_p", "r_leg_an_r", "r_leg_an_p"]

